In [1]:
from numpy import random as rd
x = rd.randint(100)
print(x)

4


In [2]:
from numpy import random as rd
x = rd.rand()    # returns float in range 0 to 1
print(x)

0.14512974506191856


In [3]:
from numpy import random as rd

x =  rd.randint(100, size=(5))  # generate an random list/array of size 5
print(x) 

[24 91 46 12 85]


In [4]:
from numpy import random as rd
x = rd.randint(100, size=(3,2)) # 2D array
print(x) 

[[29 25]
 [86 42]
 [38 17]]


In [5]:
from numpy import random as rd
x = rd.rand(2,2,2)  #float array of size 5
print(x)

[[[0.16965235 0.5195048 ]
  [0.04434205 0.17445799]]

 [[0.42402503 0.89775812]
  [0.30333702 0.87704791]]]


In [6]:
from numpy import random as rd
x = rd.choice([2,3,4,5])
print(x)

4


In [7]:
from numpy import random as rd
x = rd.choice([2,3,4,5], size = (3,2))
print(x)

[[5 3]
 [4 3]
 [3 2]]
