In [2]:
import numpy as np
arr = np.array([1,2,3,4])
x = [True,False,True,False]
newarr = arr[x]
print(newarr)

[1 3]


In [5]:
import numpy as np
arr = np.array([1,12,45,23,67,12,76,32,5,29])
filter_arr = []
[filter_arr.append(True) if elem > 15 else filter_arr.append(False) for elem in arr]
newarr = arr[filter_arr]
print(newarr)
newarr.sort()
print(newarr)

[45 23 67 76 32 29]
[23 29 32 45 67 76]


In [9]:
#instead of above code we can write it as
import numpy as np
arr = np.array([1,12,45,23,67,12,76,32,5,29])
filter_arr = arr > 15
newarr = arr[filter_arr]
print(newarr)
newarr.sort()
print(newarr)

[45 23 67 76 32 29]
[23 29 32 45 67 76]


In [10]:
import numpy as np
arr = np.array([1,12,45,23,67,12,76,32,5,29])
filter_arr = arr%2 == 0
newarr = arr[filter_arr]
print(newarr)
newarr.sort()
print(newarr)

[12 12 76 32]
[12 12 32 76]
