In [6]:
import numpy as np
#                     1                2
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np.concatenate((arr1,arr2))
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
import numpy as np
#                     1                2
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np.concatenate((arr1,arr2),axis = 1)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [21]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([7,8,9])
arr = np.stack((arr1,arr2),axis = 1)
print(arr)
print(arr.ndim)

[[1 7]
 [2 8]
 [3 9]]
2


In [17]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([7,8,9])
arr = np.hstack((arr1,arr2)) # horizontal stack
print(arr) 

[1 2 3 7 8 9]


In [18]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([7,8,9])
arr = np.vstack((arr1,arr2)) # vertical stack
print(arr)

[[1 2 3]
 [7 8 9]]


In [20]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([7,8,9])
arr = np.dstack((arr1,arr2))
print(arr)
print(arr.ndim)

[[[1 7]
  [2 8]
  [3 9]]]
3
