In [5]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr=arr2,arr3,arr4 = np.array_split(arr1,3)     #array_split --> Automatically adjust itself
print(arr)
print(arr2)
print(arr3)
print(arr4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]
[4 5 6]
[7 8 9]


In [7]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr =  np.split(arr1,3)                      #split --> manual it will fail to adjust itself
print(arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [8]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6,7,8,9])

newarr = np.array_split(arr1,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [13]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [22]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr,3,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


(array([1, 2, 4]), array([0, 1, 2]))
